### PR TITLE
Fix kruler ignore rule

### PR DESCRIPTION
**Pull request by Managor**
~~Clean install~~ and I noticed this didn't work.

EDIT: Sorry I was tired yesterday and wrote untrue things.

### CODE REVIEW

**Comment by anametologin** [comment]
`org.kde.kruler` perfectly works

**Comment by Managor** [comment]
For some reason it didn't work in my environment. Would me being on Plasma 6.2 be the cause?

**Comment by anametologin** [comment]
Plasma 6.2: `qml: krohnkite:<caption: KRuler — KDE Screen Ruler> <output.name: DP-2> <resourceName: kruler> <resourceClass: org.kde.kruler> `

**Comment by Managor** [comment]
Alright. Then I have no idea what's causing this. Maybe the fact that I was briefly opted into Arch Linux testing repos and now some package is causing issues. My desktop is now updated to 6.2 through the stable channels and `org.kde.kruler` works just fine. Meanwhile my laptop isn't accepting it.
Here's video proof of it happening: https://youtu.be/SCrtwhDKJcA

**Comment by anametologin** [comment]
let's wait may be someone else has the same problem

**Comment by mutchiko** [comment]
i can confirm: kruler gets tiled even though ```org.kde.kruler``` is in the rules, happens for both flatpak and arch packages. im not using any testing repo, currently on plasma 6.2.4 and krohnkite 0.9.8.4

**Comment by Managor** [comment]
I assume including both won't break anything.

**Comment by Managor** [comment]
Ok I found some more info on this bug. I did a completely new install on my PC and I had the ruler not obey the exception. Applying the "By Class" section once made it start obeying it. So I assume res/config.xml controls only what is shown in the settings configurator whereas kronkite pulls its settings from somewhere deeper.

**Pull request merged**
