### PR TITLE
Add package-lock.json

### PR DESCRIPTION
**Pull request by NotLebedev**
As per [npm docs](https://docs.npmjs.com/cli/v8/configuring-npm/package-lock-json) `package-lock.json`  
> is intended to be committed into source repositories, and serves various purposes
Additionally other kwin script repositories such as [polonium](https://github.com/zeroxoneafour/polonium) also commit this file, so this seems to be suitable in this usecase. 

Personally I tried to package it using nix and it won't do it without package-lock (because in general this may lead to non-reproducible build)

Thank you for your work on supporting this project!

### CODE REVIEW

**Comment by anametologin** [comment]
> is intended to be committed into source repositories, and serves various purposes

1. I've read all purposes and haven't found any reasonable for this repository. 
2. everyone can easily generate it `make package` command 
4. `package-lock.json` can be different from system to system
5. your package-lock.json is different from mine. Obviously you are using MacOS of something like this. 
6. tsc version "^5..." -frozen only major version number, but everyone can have their own minor version.

**Comment by NotLebedev** [comment]
> 1. I've read all purposes and haven't found any reasonable for this repository.
It's true that this project only has `devDependencies` and thus need for `package-lock.json` is less. However the part aqbout `continuous integration are guaranteed to install exactly the same dependencies` is exactly why I created this. Package manager can vendor `package-lock.json` but then your distribution through kde store would be different from packaged versions. Then it may be difficult to reproduce some edge cases in bug reports.

>     3. `package-lock.json` can be different from system to system
>     4. your package-lock.json is different from mine. Obviously you are using MacOS of something like this.
That's exactly my point. I'm not even using macOS, as you suggested, but still there are some differences. I'm not sure how this may change behavior of different builds and introduce problems when debugging.

In any case I agree with you that this is not a critical problem. In my opinion it's just QOL for packaging and possibly debugging some edge cases. If you believe that there is no need for this change feel free to close PR.

**Comment by anametologin** [comment]
Until this becomes a problem I will refrain from adding package-lock.json to repository.

**Comment by SuperSandro2000** [comment]
When packaging things for a distro like NixOS we need a lock file because the package should be reproducible. Right now we roll one but it would be easier if upstream had one.

**Comment by anametologin** [comment]
3c546f45065d1b47a0ef077446fa04f91f972eaa

**Pull request closed without merging**
